### ISSUE TITLE
New doc in NAS-shared folder?

### ISSUE THREAD

**Issue by jlm70** [HuangRunHua/FilerApp#5]
Hello,
I've downloaded the app from the AppStore, but before buying it I'd like to know if the "New doc" (eg. New Powerpoint file, New Text file, etc.) would work with my NAS folders, as I mainly work within my home network.
Asking this as I've read the app can only access the user folder structure...

Thanks,
g

**Comment by HuangRunHua** [comment]
Hi there,The free version can actually create file (New File function) and can meet basic needs (you just need to enable folder access first). And due to the limitations put by Apple, you can only create a new file under the path /Macintosh HD/Users/your_user_name/You can refer to the picture below:Ask me any question if something confuses you.Looking forward to hearing from you.Sent from my iPhoneOn Jun 2, 2023, at 23:11, Gianluca Meardi ***@***.***> wrote:﻿
Hello,
I've downloaded the app from the AppStore, but before buying it I'd like to know if the "New doc" (eg. New Powerpoint file, New Text file, etc.) would work with my NAS folders, as I mainly work within my home network.
Asking this as I've read the app can only access the user folder structure...
Thanks,
g

**Comment by HuangRunHua** [comment]
![Image 6-2-23 at 11 31 PM](https://github.com/HuangRunHua/FilerApp/assets/45262463/6b527648-8b80-4a43-b16d-5a156618ffb2)
