### ISSUE TITLE
How can I disable Custom Template feature?

### ISSUE THREAD

**Issue by OleksandrDovhan** [HuangRunHua/FilerApp#6]
I bought this feature, but then I realized that I don't really need it. Moreover, now to create a new file, I need to select the file type and an empty template from the drop-down menu. Earlier I just click in file type and it was creat. Any suggestions? Thanks in advance.

**Comment by HuangRunHua** [comment]
Hi 👋 there,Sorry for inconvenience of the bothering feature. Unfortunately you could not disable this feature right now but since you don’t need that feature you can just refund from App Store.Sent from my iPhoneOn Jul 7, 2023, at 15:58, OleksandrDovhan ***@***.***> wrote:﻿
I bought this feature, but then I realized that I don't really need it. Moreover, now to create a new file, I need to select the file type and an empty template from the drop-down menu. Earlier I just click in file type and it was creat. Any suggestions? Thanks in advance.

**Comment by OleksandrDovhan** [comment]
Yes I've requested a refund, but feature is still available, will it become inaccessible after refund?

**Comment by HuangRunHua** [comment]
Hi there, once it refunded the feature should disappear immediately. If not please tell me thanksSent from my iPhoneOn Jul 7, 2023, at 16:35, OleksandrDovhan ***@***.***> wrote:﻿
Yes I've requested a refund, but feature is still available, will it become inaccessible after refund?

**Comment by OleksandrDovhan** [comment]
I haven't received the money yet, but on reportaproblem.apple website shows status "reimbursed".
